const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('../app/src/main/assets/engine');
function cards(rs){const seen={};return rs.map(r=>r>=16?r+36:(r-3)*4+(seen[r]=(seen[r]||0)+1)-1);}
function seeded(seed){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
test('all supported patterns and exclusions',()=>{
 const cases=[[[3],'single'],[[4,4],'pair'],[[5,5,5],'triple'],[[6,6,6,3],'tripleSingle'],[[6,6,6,3,3],'triplePair'],[[3,4,5,6,7],'straight'],[[3,3,4,4,5,5],'pairs'],[[3,3,3,4,4,4],'plane'],[[3,3,3,4,4,4,7,7],'planeSingles'],[[3,3,3,4,4,4,7,7,8,8],'planePairs'],[[5,5,5,5,7,7],'fourSingles'],[[5,5,5,5,7,7,8,8],'fourPairs'],[[7,7,7,7],'bomb'],[[16,17],'rocket']];
 for(const [rs,t]of cases)assert.equal(E.classify(cards(rs))?.type,t,rs.join(','));
 for(const rs of [[11,12,13,14,15],[3,3,4,4],[3,3,3,4,4,4,16,17],[3,3,3,3,4,4,4,5],[5,5,5,5,16,17],[5,5,5,5,7,7,7,7]])assert.equal(E.classify(cards(rs)),null,rs.join(','));
 assert.equal(E.classify([0,0]),null);assert.equal(E.classify([54]),null);
});
test('comparisons, bomb hierarchy, equal-length sequences',()=>{const c=rs=>E.classify(cards(rs));assert(E.beats(c([4]),c([3])));assert(!E.beats(c([3]),c([3])));assert(!E.beats(c([4,4]),c([3])));assert(E.beats(c([3,3,3,3]),c([17])));assert(E.beats(c([16,17]),c([15,15,15,15])));assert(!E.beats(c([15,15,15,15]),c([16,17])));assert(!E.beats(c([4,5,6,7,8,9]),c([3,4,5,6,7])));});
test('legal move generator agrees with exhaustive subsets on small hands',()=>{const rng=seeded(82);for(let trial=0;trial<35;trial++){const hand=E.deal(rng).hands[0].slice(0,11);const targets=[null,E.classify(cards([5])),E.classify(cards([4,4]))];for(const target of targets){const expected=new Set();for(let mask=1;mask<(1<<hand.length);mask++){const cs=hand.filter((_,i)=>mask&(1<<i));if(E.beats(E.classify(cs),target))expected.add(E.sort(cs).map(E.rank).join(','));}const actual=new Set(E.moves(hand,target).map(m=>m.cards.map(E.rank).join(',')));assert.deepEqual(actual,expected);}}});
test('bidding, pass reset and invalid actions preserve state',()=>{const s=E.newGame('normal',seeded(7));s.turn=0;E.actBid(s,1);assert.throws(()=>E.actBid(s,1));E.actBid(s,0);E.actBid(s,0);assert.equal(s.landlord,0);assert.equal(s.hands[0].length,20);assert.throws(()=>E.play(s,[]));E.play(s,[s.hands[0][0]]);E.play(s,[]);E.play(s,[]);assert.equal(s.turn,0);assert.equal(s.last,null);const before=JSON.stringify(s);assert.throws(()=>E.play(s,[99]));assert.equal(JSON.stringify(s),before);});
test('all pass requests redeal',()=>{const s=E.newGame();for(let i=0;i<3;i++)E.actBid(s,0);assert.equal(s.phase,'redeal');});
test('spring and reverse spring double multiplier',()=>{for(const landlordWins of [true,false]){const s=E.newGame();Object.assign(s,{phase:'play',landlord:0,turn:landlordWins?0:1,hands:[[0],[4],[8]],played:landlordWins?[0,0,0]:[1,1,0]});E.play(s,[landlordWins?0:4]);assert.equal(s.phase,'over');assert(s.spring);assert.equal(s.multiplier,2);}});
test('AI cooperates with farmer partner and plays immediate win',()=>{const target={...E.classify(cards([3])),cards:cards([3])};const ctx={player:1,landlord:0,lastPlayer:2,counts:[3,2,2]};assert.equal(E.ai(cards([4,5]),target,ctx,'hard'),null);assert.equal(E.ai(cards([4]),target,ctx,'hard').key,4);});
test('180 seeded full games terminate legally and conserve all 54 cards',()=>{for(const level of ['easy','normal','hard'])for(let seed=1;seed<=60;seed++){const rng=seeded(seed);let s=E.newGame(level,rng),steps=0,played=[];while(s.phase!=='over'&&steps++<650){if(s.phase==='redeal'){s=E.newGame(level,rng);played=[];continue;}if(s.phase==='bid'){E.actBid(s,E.bid(s.hands[s.turn],s.highBid,level,rng));continue;}const p=s.turn,hand=s.hands[p];const m=E.ai(hand,s.last,{player:p,landlord:s.landlord,lastPlayer:s.lastPlayer,counts:s.hands.map(h=>h.length)},level,rng);if(m){assert(E.beats(E.classify(m.cards),s.last));played.push(...m.cards);}E.play(s,m?.cards||[]);const all=s.hands.flat().concat(played);assert.equal(all.length,54);assert.equal(new Set(all).size,54);}assert.equal(s.phase,'over',`${level}/${seed}`);assert.equal(s.hands[s.winner].length,0);}});
